=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/src/CADAssembler/CADCreoParametricCreateAssembly/Schema/AssemblyInterface.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?udm interface="AssemblyInterface" version="1.00"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" 
>
<!-- generated on Fri Jun 24 15:16:57 2011 -->


	<xsd:complexType name="ConstraintFeatureType">
		<xsd:attribute name="FeatureName" type="xsd:string" use="required"/>
		<xsd:attribute name="ComponentID" type="xsd:string" use="required"/>
		<xsd:attribute name="FeatureOrientationType" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="PairType">
		<xsd:sequence>
			<xsd:element name="ConstraintFeature" type="ConstraintFeatureType" minOccurs="2" maxOccurs="2"/>
			<xsd:element name="ConstraintOffset" type="ConstraintOffsetType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="FeatureGeometryType" type="xsd:string" use="required"/>
		<xsd:attribute name="FeatureInterfaceType" type="xsd:string" use="required"/>
		<xsd:attribute name="FeatureAlignmentType" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="ConstraintOffsetType">
		<xsd:sequence>
			<xsd:element name="Units" type="UnitsType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="OffsetAlignmentType" type="xsd:string" use="required"/>
		<xsd:attribute name="Value" type="xsd:double" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="CADParameterType">
		<xsd:sequence>
			<xsd:element name="Units" type="UnitsType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="Type" type="xsd:string" use="required"/>
		<xsd:attribute name="Name" type="xsd:string" use="required"/>
		<xsd:attribute name="Value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="ParametricParametersType">
		<xsd:sequence>
			<xsd:element name="CADParameter" type="CADParameterType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="UnitsType">
		<xsd:attribute name="Value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="PropertiesType">
		<xsd:sequence>
			<xsd:element name="Units" type="UnitsType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CADComponentType">
		<xsd:sequence>
			<xsd:element name="CADComponent" type="CADComponentType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Constraint" type="ConstraintType" minOccurs="0"  maxOccurs="unbounded"/>
			<xsd:element name="ParametricParameters" type="ParametricParametersType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="Name" type="xsd:string" use="required"/>
		<xsd:attribute name="ComponentID" type="xsd:string" use="required"/>
		<xsd:attribute name="Type" type="xsd:string" use="required"/>
    <xsd:attribute name="SpecialInstruction" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="AssemblyType">
		<xsd:sequence>
			<xsd:element name="CADComponent" type="CADComponentType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Properties" type="PropertiesType"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ConstraintType">
		<xsd:sequence>
			<xsd:element name="Pair" type="PairType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

 <xsd:element name="Assembly" type="AssemblyType"/>

</xsd:schema>

=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/deploy/CAD_Installs/Proe ISIS Extensions/docs/examples/Engine_Transmission_CAD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Assembly xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AssemblyInterface.xsd">

  <CADComponent ComponentID="100000052" Name="Engine_Transmission" Type="ASSEMBLY">
    <CADComponent ComponentID="100000362" Name="CAT_C9" Type="PART">
      <Constraint>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="SURFACE" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="FRONT" FeatureOrientationType="SIDE_A"/>
          <ConstraintFeature ComponentID="100000052" FeatureName="ASM_FRONT" FeatureOrientationType="SIDE_A"/>
        </Pair>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="SURFACE" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="TOP" FeatureOrientationType="SIDE_A"/>
          <ConstraintFeature ComponentID="100000052" FeatureName="ASM_TOP" FeatureOrientationType="SIDE_A"/>
        </Pair>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="SURFACE" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="RIGHT" FeatureOrientationType="SIDE_A"/>
          <ConstraintFeature ComponentID="100000052" FeatureName="ASM_RIGHT" FeatureOrientationType="SIDE_A"/>
        </Pair>
      </Constraint>
    </CADComponent>
    <CADComponent ComponentID="100000487" Name="CAT_CX31" Type="PART">
      <Constraint>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="SURFACE" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="FLYWHEEL_HOUSING_MNT_SURF" FeatureOrientationType="SIDE_A"/>
          <ConstraintFeature ComponentID="100000487" FeatureName="FLYWHEEL_HOUSING_MNT_SURF" FeatureOrientationType="SIDE_B"/>
        </Pair>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="AXIS" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="FLYWHEEL_HOUSING_BTM_BOLT_AXIS" FeatureOrientationType="NONE"/>
          <ConstraintFeature ComponentID="100000487" FeatureName="FLYWHEEL_HOUSING_BTM_BOLT_AXIS" FeatureOrientationType="NONE"/>
        </Pair>
        <Pair FeatureAlignmentType="ALIGN" FeatureGeometryType="AXIS" FeatureInterfaceType="CAD_DATUM">
          <ConstraintFeature ComponentID="100000362" FeatureName="DRIVE_AXIS" FeatureOrientationType="NONE"/>
          <ConstraintFeature ComponentID="100000487" FeatureName="DRIVE_AXIS" FeatureOrientationType="NONE"/>
        </Pair>
      </Constraint>
    </CADComponent>
  </CADComponent>

  <Properties>
    <Units Value="value1"/>
  </Properties>

</Assembly>
