=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/meta/DesignDataPackage/schema/AssemblyDetails.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:iFAB="iFAB" targetNamespace="iFAB">

  <xs:annotation>
    <xs:appinfo>iFAB Foundry Assembly Details XML Schema</xs:appinfo>
    <xs:documentation xml:lang="en">This schema defines an XML file for representing assembly details.</xs:documentation>
  </xs:annotation>

  <xs:include schemaLocation="common.xsd" />

  <xs:element name="assemblyDetails" type="iFAB:assemblyDetails" />

  <xs:complexType name="assemblyDetails">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="assemblyDetail" type="iFAB:assemblyDetail" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="assemblyDetail">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0" />
      <xs:element name="part1" type="iFAB:partReference" />
      <xs:element name="part2" type="iFAB:partReference" />
      <xs:element name="description" type="xs:string" minOccurs="0" />
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="incidentalContact" type="iFAB:incidentalContact" />
        <xs:element name="mechanical" type="iFAB:mechanical" />
        <xs:element name="welded" type="iFAB:welded" />
        <xs:element name="soldered" type="iFAB:soldered" />
        <xs:element name="brazed" type="iFAB:brazed" />
        <xs:element name="glued" type="iFAB:glued" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute ref="iFAB:id" use="required" />
  </xs:complexType>

  <xs:complexType name="incidentalContact">
    <xs:sequence>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="mechanical">
    <xs:sequence>
      <xs:element name="linkingPart" type="iFAB:partReference" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="notes" type="xs:string" minOccurs="0" />
      <xs:element name="fasteningMethod" type="iFAB:fasteningMethod" />
      <xs:element name="fasteningQuantity" type="xs:positiveInteger" minOccurs="0" default="1" />
      <xs:element name="torque" type="iFAB:torque" minOccurs="0" />
      <xs:element name="force" type="iFAB:force" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="welded">
    <xs:sequence>
      <xs:element name="linkingPart" type="iFAB:partReference" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="notes" type="xs:string" minOccurs="0" />
      <xs:element name="length" type="iFAB:length" />
      <xs:element name="jointType" type="iFAB:jointType" />
      <xs:element name="weldType" type="iFAB:weldType" />
      <xs:element name="weldPenetration" type="iFAB:weldPenetration" />
      <xs:element name="twoSided" type="xs:boolean" />
      <xs:element name="inspectionRequirement" type="iFAB:inspectionRequirement" />
      <xs:element name="part1Thickness" type="iFAB:length" />
      <xs:element name="part1Material" type="iFAB:baseMaterial" />
      <xs:element name="part2Thickness" type="iFAB:length" />
      <xs:element name="part2Material" type="iFAB:baseMaterial" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="soldered">
    <xs:sequence>
      <xs:element name="linkingPart" type="iFAB:partReference" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="notes" type="xs:string" minOccurs="0" />
      <xs:element name="length" type="iFAB:length" />
      <xs:element name="fillerMaterial" type="iFAB:fillerMaterial" />
      <xs:element name="fluxMaterial" type="iFAB:fluxMaterial" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="brazed">
    <xs:sequence>
      <xs:element name="linkingPart" type="iFAB:partReference" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="notes" type="xs:string" minOccurs="0" />
      <xs:element name="length" type="iFAB:length" />
      <xs:element name="fillerMaterial" type="iFAB:fillerMaterial" />
      <xs:element name="fluxMaterial" type="iFAB:fluxMaterial" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="glued">
    <xs:sequence>
      <xs:element name="linkingPart" type="iFAB:partReference" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="notes" type="xs:string" minOccurs="0" />
      <xs:element name="length" type="iFAB:length" />
      <xs:element name="volume" type="iFAB:volume" />
      <xs:element name="material" type="iFAB:glue" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="baseMaterial">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Al" />
      <xs:enumeration value="Plain Carbon Steel" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fillerMaterial">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="fluxMaterial">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="glue">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="fasteningMethod">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Bolted" />
      <xs:enumeration value="Bolted (blind)" />
      <xs:enumeration value="Machined Screw" />
      <xs:enumeration value="Press Fit" />
      <xs:enumeration value="Snap Fit" />
      <xs:enumeration value="Crimp/Clamp Fit" />
    </xs:restriction>
  </xs:simpleType>
              
  <xs:simpleType name="jointType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Butt" />
      <xs:enumeration value="Corner" />
      <xs:enumeration value="Edge" />
      <xs:enumeration value="Lap" />
      <xs:enumeration value="Tee" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weldType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Seam" />
      <xs:enumeration value="Stitch" />
      <xs:enumeration value="Spot" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weldPenetration">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Full" />
      <xs:enumeration value="Partial" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="inspectionRequirement">
    <xs:restriction base="xs:token">
      <xs:enumeration value="Visual" />
      <xs:enumeration value="X-Ray" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="partReference">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="iFAB:id" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/meta/DesignDataPackage/iFAB/assemblyExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<iFAB:assemblyDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:iFAB="iFAB" xsi:schemaLocation="iFAB assemblyDetails.xsd">
  <assemblyDetail iFAB:id="8a4ef431-f389-ab12-c188-837abf730112">
    <part1 iFAB:id="9024f261-3e8b-4949-bbae-8befab573b07">PLATE, UPPER HARDSTOP, ELEVATOR</part1>
    <part2 iFAB:id="1ac869a4-a144-4908-bc99-e7f7bb329255">BRACKET 1, ELVATOR HARDSTOP</part2>
    <mechanical>
      <linkingPart iFAB:id="b3c87fc1-370b-4337-b2bb-637b5f34e763">Hex Bolt (3 x 3/80)</linkingPart>
      <linkingPart iFAB:id="11a5c226-2deb-40f2-9120-ff3623ce4c41">Nut (3/8 x 1/4)</linkingPart>
      <linkingPart iFAB:id="2a2ab244-f48a-4326-b894-7822b08e036b">Washer, Flat (3/8)</linkingPart>
      <notes>Bolt Bracket 1 to Plate</notes>
      <fasteningMethod>Bolted</fasteningMethod>
      <fasteningQuantity>3</fasteningQuantity>
      <torque unit="N m">62.5</torque>
    </mechanical>
  </assemblyDetail>
  <assemblyDetail iFAB:id="82bd115c-f112-a19d-dd11-839001cc1adf">
    <part1 iFAB:id="9024f261-3e8b-4949-bbae-8befab573b07">PLATE, UPPER HARDSTOP, ELEVATOR</part1>
    <part2 iFAB:id="d2e519a6-47d8-4908-9bba-a34b3e56a3a0">PLATE, PIN MOUNT, ELEVATOR</part2>
    <welded>
      <length unit="in">10.75</length>
      <jointType>Edge</jointType>
      <weldType>Seam</weldType>
      <weldPenetration>Partial</weldPenetration>
      <twoSided>false</twoSided>
      <inspectionRequirement>X-Ray</inspectionRequirement>
      <part1Thickness unit="in">0.5</part1Thickness>
      <part1Material>Al</part1Material>
      <part2Thickness unit="in">0.25</part2Thickness>
      <part2Material>Al</part2Material>
    </welded>
  </assemblyDetail>
  <assemblyDetail iFAB:id="8e1b9bc1-91d5-4046-bb06-9dd1b32db6ca">
    <part1 iFAB:id="92ea91e6-a42a-4fe6-9f80-236d83d0eafd" />
    <part2 iFAB:id="24e00e11-8d59-497e-83c1-397cf2d0a97d" />
    <soldered>
      <length unit="cm">0.75</length>
      <fillerMaterial>60/40</fillerMaterial>
      <fluxMaterial>Rosin</fluxMaterial>
    </soldered>
  </assemblyDetail>
  <assemblyDetail iFAB:id="9f4dc488-39b7-4670-9859-e5df7a571bde">
    <part1 iFAB:id="0789f65d-41d1-4024-92d8-c707f9e91ac0" />
    <part2 iFAB:id="ebb96825-51ec-41b4-bcd0-0ebf1570f0d8" />
    <brazed>
      <length unit="in">2.75</length>
      <fillerMaterial>Aluminum-silicon</fillerMaterial>
      <fluxMaterial>Borax</fluxMaterial>
    </brazed>
  </assemblyDetail>
  <assemblyDetail iFAB:id="321c5d09-7fe9-447f-bb3f-b1c3bcbae8bb">
    <part1 iFAB:id="059867d4-4556-44f2-991a-6953e40e8dd0" />
    <part2 iFAB:id="851ba6db-5da9-43f7-bf25-57032c9114ec" />
    <glued>
      <length unit="in">6.125</length>
      <volume unit="in3">0.75</volume>
      <material>Loctite 243</material>
    </glued>
  </assemblyDetail>
</iFAB:assemblyDetails>
