=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/meta/DesignDataPackage/iFAB/hudat.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:iFAB="iFAB" targetNamespace="iFAB">

  <xs:annotation>
    <xs:appinfo>iFAB Foundry Hull Design and Analysis Tool XML Schema</xs:appinfo>
    <xs:documentation xml:lang="en">This schema defines an XML file for representing the input data to the HuDAT software.</xs:documentation>
  </xs:annotation>

  <xs:include schemaLocation="common.xsd" />

	<xs:element name="hudatWelds">
		<xs:complexType>
			<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1" name="hudatWeld" type="iFAB:hudatWeld"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="hudatWeld" xmlns="iFAB">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="componentClass" type="xs:string" />
			<xs:element name="UUID" type="guid" />
			<xs:element name="instanceID" type="xs:string" />
			<xs:element name="jointType" type="jointType" />
			<xs:element name="grooveConfiguration" type="grooveConfiguration" />
			<xs:element name="weldJointConfiguration" type="weldJointConfiguration" />
			<xs:element name="weldPenetration" type="weldPenetration" />
			<xs:element name="doubleSided" type="xs:boolean" />
			<xs:element name="materialWeldCompatible" type="xs:boolean" />
			<xs:element name="weldProcess" type="weldProcess" />
			<xs:element name="inspectionReqt" type="xs:string" />
			<xs:element name="weldLength" type="length" />
			<xs:element name="jointStrengthReqt" type="pressure" />
			<xs:element name="jointElongationReqt" type="xs:double" />
			<xs:element name="fillerMaterialSpec" type="fillerMaterial" />
			<xs:element name="weldSide1" type="weldSide" />
			<xs:element name="weldSide2" type="weldSide" minOccurs="0" />
			<xs:element name="part1" type="part" />
			<xs:element name="part2" type="part" />
		</xs:sequence>
	</xs:complexType>

  <xs:complexType name="weldSide" xmlns="iFAB">
    <xs:sequence>
      <xs:element name="incAngle" type="angle" />
      <xs:element name="leg1Length" type="length" />
      <xs:element name="leg2Length" type="length" />
      <xs:element name="weldArea" type="area" />
      <xs:element name="weldVolume" type="volume" />
    </xs:sequence>
  </xs:complexType>
  
    <!-- TODO: Need a proper definition of material -->
	<xs:complexType name="material" xmlns="iFAB">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
						
  <xs:complexType name="part" xmlns="iFAB">
    <xs:sequence>
      <xs:element name="id" type="guid" />
      <xs:element name="stockNumber" type="xs:string" />
	  <xs:element name="creoName" type="xs:string" />
	  <xs:element name="stepName" type="xs:string" />
      <xs:element name="thickness" type="length" />
      <xs:element name="material" type="material" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="jointType" xmlns="iFAB">
    <xs:restriction base="xs:token">
      <xs:enumeration value="tee" />
      <xs:enumeration value="butt" />
      <xs:enumeration value="corner" />
      <xs:enumeration value="skewedplate" />
      <xs:enumeration value="edge" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="grooveConfiguration" xmlns="iFAB">
    <xs:restriction base="xs:token">
      <xs:enumeration value="square" />
      <xs:enumeration value="v" />
      <xs:enumeration value="bevel" />
      <xs:enumeration value="double v" />
      <xs:enumeration value="double bevel" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weldJointConfiguration" xmlns="iFAB">
    <xs:restriction base="xs:token">
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weldPenetration" xmlns="iFAB">
    <xs:restriction base="xs:token">
      <xs:enumeration value="partial" />
      <xs:enumeration value="complete" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="weldProcess" xmlns="iFAB">
    <xs:restriction base="xs:token">
      <xs:enumeration value="GMAW" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fillerMaterial">
    <xs:restriction base="xs:token">
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/meta/DesignDataPackage/iFAB/hudatExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<iFAB:hudatWelds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:iFAB="iFAB" xsi:schemaLocation="iFAB hudat.xsd">
	<hudatWeld>
		<name>Weld_AB</name>
		<componentClass>HuDATWeld</componentClass>
		<UUID>Weld_AB_1234</UUID>
    		<instanceID>Weld_AB_1234.1</instanceID>
		<jointType>corner</jointType>
		<grooveConfiguration>custom</grooveConfiguration>
		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
		<weldPenetration>full</weldPenetration>
		<doubleSided>true</doubleSided>
		<materialWeldCompatible>true</materialWeldCompatible>
		<weldProcess>GMAW</weldProcess>
		<inspectionReqt>Visual</inspectionReqt>
		<weldLength unit="mm">6883.6</weldLength>
		<jointStrengthReqt unit="Mpa" >938</jointStrengthReqt>
		<jointElongationReqt>12</jointElongationReqt>
		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
		<weldSide1>
			<incAngle unit = "degrees">90</incAngle>
			<leg1Length unit="mm">22.225</leg1Length>
			<leg2Length unit="mm">22.22</leg2Length>
			<weldArea unit="mm2">246.9</weldArea>
			<weldVolume unit="mm3">1700076</weldVolume>
		</weldSide1>
		<weldSide2>
			<incAngle unit = "degrees">90</incAngle>
			<leg1Length unit="mm">22.225</leg1Length>
			<leg2Length unit="mm">22.225</leg2Length>
			<weldArea unit="mm2">246.9</weldArea>
			<weldVolume unit="mm3">1700076</weldVolume>
		</weldSide2>
		<part1>
			<id>140_PANEL_A_DET</id>
			<stockNumber>stockNumber</stockNumber>
			<thickness unit="mm">25.40</thickness>
			<material id="Steel MIL-DTL-12560">material</material>
		</part1>
		<part2>
			<id>140_PANEL_B_DET</id>
			<stockNumber>stockNumber</stockNumber>
			<thickness unit="mm">25.40</thickness>
			<material id="Steel MIL-DTL-12560">material</material>
		</part2>
	</hudatWeld>
	<hudatWeld>
		<name>Weld_AH</name>
  		<componentClass>HuDATWeld</componentClass>
  		<UUID>Weld_AH_1234</UUID>
  		<instanceID>Weld_AH_1234.1</instanceID>
  		<jointType>corner</jointType>
  		<grooveConfiguration>custom</grooveConfiguration>
  		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
  		<weldPenetration>full</weldPenetration>
  		<doubleSided>true</doubleSided>
  		<materialWeldCompatible>true</materialWeldCompatible>
  		<weldProcess>GMAW</weldProcess>
  		<inspectionReqt>X-Ray</inspectionReqt>
  		<weldLength unit="mm">6883.6</weldLength>
  		<jointStrengthReqt unit="Mpa">938</jointStrengthReqt>
  		<jointElongationReqt>12</jointElongationReqt>
  		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
  		<weldSide1>
    			<incAngle>90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.22</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume unit="mm3">1700076</weldVolume>
  		</weldSide1>
  		<weldSide2>
    			<incAngle unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.225</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume unit="mm3">1700076</weldVolume>
  		</weldSide2>
  		<part1>
    			<id>140_PANEL_A_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part1>
  		<part2>
    			<id>140_PANEL_H_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part2>
	</hudatWeld>
	<hudatWeld>
		<name>Weld_AL</name>
		<componentClass>HuDATWeld</componentClass>
  		<UUID>Weld_AL_1234</UUID>
  		<instanceID>Weld_AL_1234.1</instanceID>
  		<jointType>skewedplate</jointType>
  		<grooveConfiguration>custom</grooveConfiguration>
  		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
  		<weldPenetration>full</weldPenetration>
  		<doubleSided>true</doubleSided>
  		<materialWeldCompatible>true</materialWeldCompatible>
  		<weldProcess>GMAW</weldProcess>
  		<inspectionReqt>X-Ray</inspectionReqt>
  		<weldLength unit="mm">3660</weldLength>
  		<jointStrengthReqt unit="Mpa">938</jointStrengthReqt>
  		<jointElongationReqt>12</jointElongationReqt>
  		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
  		<weldSide1>
    			<incAngle>90</incAngle>
    			<leg1Length unit="mm">22.23</leg1Length>
    			<leg2Length unit="mm">22.23</leg2Length>
    			<weldArea unit="mm2">247.0</weldArea>
    			<weldVolume unit="mm3">904336</weldVolume>
  		</weldSide1>
  		<weldSide2>
    			<incAngle unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.23</leg1Length>
    			<leg2Length unit="mm">22.23</leg2Length>
    			<weldArea unit="mm2">247.0</weldArea>
    			<weldVolume unit="mm3">904336</weldVolume>
  		</weldSide2>
  		<part1>
    			<id>140_PANEL_A_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part1>
  		<part2>
    			<id>140_PANEL_L_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part2>
	</hudatWeld>
	<hudatWeld>
	  	<name>Weld_CB</name>
  		<componentClass>HuDATWeld</componentClass>
  		<UUID>Weld_CB_1234</UUID>
  		<instanceID>Weld_CB_1234.1</instanceID>
  		<jointType>corner</jointType>
  		<grooveConfiguration>custom</grooveConfiguration>
  		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
  		<weldPenetration>full</weldPenetration>
  		<doubleSided>true</doubleSided>
  		<materialWeldCompatible>true</materialWeldCompatible>
  		<weldProcess>GMAW</weldProcess>
  		<inspectionReqt>Visual</inspectionReqt>
  		<weldLength unit="mm">7482</weldLength>
  		<jointStrengthReqt unit="Mpa">938</jointStrengthReqt>
  		<jointElongationReqt>12</jointElongationReqt>
  		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
  		<weldSide1>
    			<incAngle unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.22</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume unit="mm3">1848064</weldVolume>
  		</weldSide1>
  		<weldSide2>
    			<incAngle unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.225</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume unit="mm3">1848064</weldVolume>
  		</weldSide2>
  		<part1>
    			<id>140_PANEL_C_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part1>
  		<part2>
    			<id>140_PANEL_B_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness unit="mm">25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part2>
	</hudatWeld>
	<hudatWeld>
  		<name>Weld_DC</name>
  		<componentClass>HuDATWeld</componentClass>
  		<UUID>Weld_DC_1234</UUID>
  		<instanceID>Weld_DC_1234.1</instanceID>
  		<jointType>corner</jointType>
  		<grooveConfiguration>custom</grooveConfiguration>
  		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
  		<weldPenetration>full</weldPenetration>
  		<doubleSided>true</doubleSided>
  		<materialWeldCompatible>true</materialWeldCompatible>
  		<weldProcess>GMAW</weldProcess>
  		<inspectionReqt>Visual</inspectionReqt>
  		<weldLength  unit="mm">7482</weldLength>
  		<jointStrengthReqt  unit="Mpa">938</jointStrengthReqt>
  		<jointElongationReqt>12</jointElongationReqt>
  		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
  		<weldSide1>
    			<incAngle unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length  unit="mm">22.22</leg2Length>
    			<weldArea  unit="mm2">246.9</weldArea>
    			<weldVolume  unit="mm3">1848064</weldVolume>
  		</weldSide1>
  		<weldSide2>
    			<incAngle  unit="degrees">90</incAngle>
    			<leg1Length unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.225</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume  unit="mm3">1848064</weldVolume>
  		</weldSide2>
  		<part1>
    			<id>140_PANEL_D_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness>25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part1>
  		<part2>
    			<id>140_PANEL_C_DET</id>
    			<stockNumber>stockNumber</stockNumber>
    			<thickness>25.40</thickness>
    			<material id="Steel MIL-DTL-12560">material</material>
  		</part2>
	</hudatWeld>
	<hudatWeld>
  		<name>Weld_ED</name>
  		<componentClass>HuDATWeld</componentClass>
  		<UUID>Weld_ED_1234</UUID>
  		<instanceID>Weld_ED_1234.1</instanceID>
  		<jointType>corner</jointType>
  		<grooveConfiguration>custom</grooveConfiguration>
  		<weldJointConfiguration>ballistic fillet fillet</weldJointConfiguration>
  		<weldPenetration>full</weldPenetration>
  		<doubleSided>true</doubleSided>
  		<materialWeldCompatible>true</materialWeldCompatible>
  		<weldProcess>GMAW</weldProcess>
  		<inspectionReqt>Visual</inspectionReqt>
  		<weldLength  unit="mm">6843.5</weldLength>
  		<jointStrengthReqt  unit="Mpa">938</jointStrengthReqt>
  		<jointElongationReqt>12</jointElongationReqt>
  		<fillerMaterialSpec>ERS100S</fillerMaterialSpec>
  		<weldSide1>
    			<incAngle  unit="degrees">90</incAngle>
    			<leg1Length  unit="mm">22.225</leg1Length>
    			<leg2Length unit="mm">22.22</leg2Length>
    			<weldArea unit="mm2">246.9</weldArea>
    			<weldVolume  unit="mm3">1690175</weldVolume>
  		</weldSide1>
  		<weldSide2>
    			<incAngle  unit="degrees">90</incAngle>
