=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/src/CADAssembler/CADCreoParametricComputeMetrics/Schema/ComputeMetricsXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?udm interface="AssemblyInterface" version="1.00"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" 
>

	<xsd:complexType name="CADIncrementParameterType">
		<xsd:sequence>
			<xsd:element name="Units" type="UnitsType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="Type" type="xsd:string" use="required"/>
		<xsd:attribute name="Name" type="xsd:string" use="required"/>
		<xsd:attribute name="StartValue" type="xsd:string" use="required"/>
    <xsd:attribute name="EndValue" type="xsd:string" use="required"/>
    <xsd:attribute name="Increment" type="xsd:string" use="required"/>
	</xsd:complexType>

  <xsd:complexType name="CADReadParameterType">
    <xsd:attribute name="Owner" type="xsd:string" use="required"/>
    <xsd:attribute name="Name" type="xsd:string" use="required"/>

  </xsd:complexType>  
  
	<xsd:complexType name="IncrementType">
		<xsd:sequence>
			<xsd:element name="CADIncrementParameter" type="CADIncrementParameterType" minOccurs="0" maxOccurs="unbounded"/>   
    </xsd:sequence>
	</xsd:complexType>

  <xsd:complexType name="ReadType">
    <xsd:sequence>
      <xsd:element name="CADReadParameter" type="CADReadParameterType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ParametricParametersType">
    <xsd:sequence>
      <xsd:element name="Increment" type="IncrementType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="Read" type="ReadType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="UnitsType">
		<xsd:attribute name="Value" type="xsd:string" use="required"/>
	</xsd:complexType>


	<xsd:complexType name="CADComponentType">
		<xsd:sequence>
			<xsd:element name="ParametricParameters" type="ParametricParametersType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="Name" type="xsd:string" use="required"/>
		<xsd:attribute name="Type" type="xsd:string" use="required"/>
    <xsd:attribute name="MetricsOutputFile" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="CADComponentsType">
		<xsd:sequence>
			<xsd:element name="CADComponent" type="CADComponentType" minOccurs="0"  maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


 <xsd:element name="CADComponents" type="CADComponentsType"/>

</xsd:schema>

=== Wushaowei001/metamorphosys-desktop/metamorphosys/META/deploy/CAD_Installs/Proe ISIS Extensions/docs/examples/compute_metrics_ptc/ComputeMetricsExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<CADComponents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComputeMetricsXML.xsd">

    <!-- Type = PART or ASSEMBLY -->
    <CADComponent  Name="bracket_01" Type="PART" MetricsOutputFile="bracket_01_metrics.csv">
      <ParametricParameters>

        <Increment> <!-- Increment is optional. -->
          <!-- Type = FLOAT, No other types currently supported.   -->
          <CADIncrementParameter Type="FLoaT" Name="UPPER_SECTION_HEIGHT" StartValue="500.0" EndValue="2000.0" Increment="500.0">
             <Units Value="MM"/>  <!-- Units optional, Not currently used.  For now, the model units will be used. -->
          </CADIncrementParameter> 
          <CADIncrementParameter Type="FLoaT" Name="WidTH"       StartValue="1000.0" EndValue="2000.0" Increment="200.0" />
          <CADIncrementParameter Type="FLoaT" Name="BASE_HEIGHT" StartValue="500.0"  EndValue="5000.0" Increment="1000.0" />
        </Increment>
 
        <Read>  <!-- Read is optional. -->
          <!-- If the owner is the current part/assembly then set Owner="MODEL"; otherwise,
               owner should be set to the Owner name in the Parameters Table (i.e. Tools 
               Parameters "Filter by" "Current and all sublevels") 
               
               Pro/E Paramter-Table types of Integer, "Real Number", String, and "Yes No" are supported.
          -->
          <CADReadParameter Owner="TOP_PLATE_ATTACH_SURF" Name="AREA_TOP_PLATE_ATTACH_SURF" />
          <CADReadParameter Owner="SIDE_SURF"             Name="AREA_SIDE_SURF" />   
        </Read>

      </ParametricParameters>

    </CADComponent>


    <!-- An example with only Increment Parameters -->
    <CADComponent  Name="plate_01" Type="PART" MetricsOutputFile="plate_01_metrics.csv">
      <ParametricParameters>
        <Increment>
          <CADIncrementParameter Type="FLoaT" Name="HEIGHT" StartValue="100.0" EndValue="400.0" Increment="50.0" />
          <CADIncrementParameter Type="FLoaT" Name="WidTH" StartValue="1000.0" EndValue="2000.0" Increment="100.0" />
         </Increment>
      </ParametricParameters>
    </CADComponent>


  <!-- An example with only Read Parameters -->
  <CADComponent  Name="bracket_01" Type="PART" MetricsOutputFile="bracket_01_read_only_metrics.csv">
   
    <ParametricParameters>
       <Read>
        <CADReadParameter Owner="MODEL"     Name="ModELED_BY" />
        <CADReadParameter Owner="MOdeL"     Name="COuNT" />
        <CADReadParameter Owner="MODEL"     Name="SHOW_WHEELS" />
        <CADReadParameter Owner="SIDE_SURF" Name="AREA_SIDE_SURF" />
      </Read>
    </ParametricParameters>

  </CADComponent>
        
</CADComponents>
